### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by JFC-MC** [asuiu/pyxtension#1]
Hello

Is there any plans to standardize installation process with pip? 
P.S. Thank you for such a convenient library!

**Comment by asuiu** [comment]
Hello.
I've made it available on PyPi [here](https://pypi.python.org/pypi/pyxtension/1.0)

Now you can just run `pip install pyxtension` and it should work. Let me know if it doesn't.

**Comment by asuiu** [comment]
Please, don't hesitate do add suggestions for new functionalities, or contribute to this repository.

**Comment by JFC-MC** [comment]
Thanks a lot!
