### ISSUE TITLE
multiprocessing method mpmap() raises error even for the sample case provided

### ISSUE THREAD

**Issue by serge-sasov** [asuiu/pyxtension#15]
Hi Andrei ,

For the sample given:
 
```
corpus = [
        "MapReduce is a programming model and an associated implementation for processing and generating large data sets with a parallel, distributed algorithm on a cluster.",
        "At Google, MapReduce was used to completely regenerate Google's index of the World Wide Web",
        "Conceptually similar approaches have been very well known since 1995 with the Message Passing Interface standard having reduce and scatter operations."]

    def reduceMaps(m1, m2):
        for k, v in m2.iteritems():
            m1[k] = m1.get(k, 0) + v
        return m1

    word_counts = stream(corpus). \
        mpmap(lambda line: stream(line.lower().split(' ')).countByValue()). \
        reduce(reduceMaps)

```

The processing results in following error:
Traceback (most recent call last):
  File "C:\Users\ses\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 537, in _handle_tasks
    put(task)
  File "C:\Users\ses\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\ses\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x00000183A90173A0>: attribute lookup <lambda> on __main__ failed

Similar error occurs with other case like:
```
result = stream([v for v in entry_list.values()]). \
            mpmap(lambda entry: TwigBasic.split_multiple_yang_structures_in_one_line(entry) if TwigBasic._check_for_twig(entry) else [entry]). \
            flatMap(). \
            enumerate(). \
            map(lambda item: (str(item[0]), item[1])). \
            toMap()
```

Could you pls have a look on it!
Best regards,
Serge

**Comment by asuiu** [comment]
Hi @serge-sasov ,
I apologize for this so late answer, for some reasons the notification of this issue didn't reach my inbox.

This is an expected behavior in Python as standard multiprocess library  uses Pickle to serialize functions, and lambda functions aren't pickle-able. Please - use [this StackOverflow](https://stackoverflow.com/a/4827520/691343) answer with workaround how to overcome this issue.
