### ISSUE TITLE
explicit agree on license changing

### ISSUE THREAD

**Issue by sergmain** [asuiu/pyxtension#16]
for changing from GPL to MIT type of licenses, the explicit agree from all contributors, including  @asuiu @marian-rusu , must be collected

**Comment by asuiu** [comment]
> for changing from GPL to MIT type of licenses, the explicit agree from all contributors, including @asuiu @marian-rusu , must be collected

Why? For example - if one of the contributors is dead, the code-base can't change it's license anymore forever?

**Comment by asuiu** [comment]
Closed due to inactivity

**Comment by sergmain** [comment]
Sorry for necro, but for your case ' if one of the contributors is dead' the confirmation still required from heirs. there are a lot of legal cases which you can google or look at cases here - https://law.stackexchange.com/search?q=license

**Comment by asuiu** [comment]
@sergmain How this agreement is collected? The PR with the license change should be accepted by them, or there's another juridical procedure for this?

**Comment by sergmain** [comment]
If I'm not mistaken,  at Jul 27, 2022 when I opened this ticket there were only 2 contributors with gpl license - you and @marian-rusu . If so, @marian-rusu can just post here that he agree to switch license. Otherwise you need to collect a list who was contributor to gpl-licensed code and ask everyone for confirmation.

**Comment by asuiu** [comment]
> If I'm not mistaken, at Jul 27, 2022 when I opened this ticket there were only 2 contributors with gpl license - you and @marian-rusu . If so, @marian-rusu can just post here that he agree to switch license. Otherwise you need to collect a list who was contributor to gpl-licensed code and ask everyone for confirmation.

The word "here" is still ambiguous from the juridical point of view. Can you be more precise?
Here - meaning this discussion thread? What is the formulation of agreement as well? is it enough just "agree" - or "agree with ...", and what are other aspects of proper agreement?

**Comment by sergmain** [comment]
> The word "here" is still ambiguous from the juridical point of view. Can you be more precise? Here - meaning this discussion thread? What is the formulation of agreement as well? is it enough just "agree" - or "agree with ...", and what are other aspects of proper agreement?

Here - meaning this discussion thread? - yes
What is the formulation of agreement as well? - something like that - https://cla.pivotal.io/
